version: '3.8'

services:
  web:
    build: .
    command: python /djangoPost/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangoPost
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    
